language: smalltalk
sudo: false

os:
  - linux
  - osx

smalltalk:
  - Pharo-7.0

env:
  matrix:
    - CI_CONFIG=.smalltalk.Unit.ston

install:
  ( cd /home/travis/build/; mkdir gracelang ; cd gracelang ; git clone https://github.com/gracelang/minigrace.git )

script:
  - travis_wait 10 "$SMALLTALK_CI_HOME/run.sh" ${CI_CONFIG}
