language: smalltalk
sudo: false

os:
  - linux

smalltalk:
  - Pharo-7.0
  - Pharo-6.1

env:
  matrix:
    - CI_CONFIG=.smalltalk.Unit.ston

script:
  - travis_wait 10 "$SMALLTALK_CI_HOME/run.sh" ${CI_CONFIG}
