generated
reduceTable
^#(
	#(15 0 #reduceActionFor__Expression__newline____1:) 
	#(8 1 #reduceActionForExpressionList1:) 
	#(12 1 #reduceActionForOuter1:) 
	#(7 1 #reduceActionForIdentifier1:) 
	#(16 1 #reduceActionForExpression1:) 
	#(15 2 #reduceActionFor__Expression__newline____2:) 
	#(10 1 #reduceActionFor_newline__1:) 
	#(11 2 #reduceActionFor__Expression__newline___1:) 
	#(16 3 #reduceActionForExpression3:) 
	#(12 3 #reduceActionForOuter2:) 
	#(16 3 #reduceActionForExpression4:) 
	#(10 2 #reduceActionFor_newline__2:)
	).