generated
scan24X23
	currentCharacter == $d
		ifTrue: [ ^ self scan54 ].
	currentCharacter == $e
		ifTrue: [ ^ self scan57 ].
	currentCharacter == $f
		ifTrue: [ ^ self scan60 ].
	currentCharacter == $i
		ifTrue: [ ^ self scan61 ].
	currentCharacter == $m
		ifTrue: [ ^ self scan68 ].
	currentCharacter == $o
		ifTrue: [ ^ self scan70 ].
	currentCharacter == $p
		ifTrue: [ ^ self scan77 ].
	currentCharacter == $r
		ifTrue: [ ^ self scan80 ].
	currentCharacter == $s
		ifTrue: [ ^ self scan84 ].
	currentCharacter == $t
		ifTrue: [ ^ self scan86 ].
	currentCharacter == $u
		ifTrue: [ ^ self scan24X6 ].
	currentCharacter == $v
		ifTrue: [ ^ self scan24X7 ].
	currentCharacter == $w
		ifTrue: [ ^ self scan88 ].
	^ self scan24X22