generated
scan80
	self recordMatch: #(40 55).
	self step.
	currentCharacter == $/
		ifTrue: [ ^ self scan81 ].
	(currentCharacter == $!
		or: [ (currentCharacter between: $# and: $&)
				or: [ (currentCharacter between: $* and: $+)
						or: [ (currentCharacter between: $- and: $.)
								or: [ currentCharacter == $:
										or: [ (currentCharacter between: $< and: $@)
												or:
													[ '\^|~' includes: currentCharacter ] ] ] ] ] ])
		ifTrue: [ ^ self scan79 ].
	^ self scan80X2