generated
scan25
	self recordMatch: #(55).
	(self scanForString: 'rr')
		ifTrue:
			[ ^ self scan25X1 ].
	(currentCharacter == $'
		or: [ (currentCharacter between: $0 and: $9)
				or: [ (currentCharacter between: $A and: $Z)
						or: [ currentCharacter == $_
								or: [ (currentCharacter between: $a and: $q)
										or: [ (currentCharacter between: $s and: $z)
												or: [ ('µæ' includes: currentCharacter)
														or: [ currentCharacter = (Character value: 960) ] ] ] ] ] ] ])
		ifTrue: [ [ self recordMatch: #(55).
			self step.
			currentCharacter == $'
				or: [ (currentCharacter between: $0 and: $9)
						or: [ (currentCharacter between: $A and: $Z)
								or: [ currentCharacter == $_
										or: [ (currentCharacter between: $a and: $z)
												or: [ ('µæ' includes: currentCharacter)
														or: [ currentCharacter = (Character value: 960) ] ] ] ] ] ] ]
				whileTrue ].
	^ self reportLastMatch