generated
scan31X2
	currentCharacter == $u
		ifTrue: [ ^ self scan29 ].
	(currentCharacter isConnectorPunctuation
		or:
			[ '"lnrt{}' includes: currentCharacter ])
		ifTrue: [ ^ self scan26 ].
	(currentCharacter isDashPunctuation
		or: [ currentCharacter == $!
				or: [ (currentCharacter between: $# and: $&)
						or: [ (currentCharacter between: $* and: $+)
								or: [ (currentCharacter between: $. and: $/)
										or: [ currentCharacter == $:
												or: [ (currentCharacter between: $< and: $@)
														or: [ ('^|~' includes: currentCharacter)
																or: [ (currentCharacter
																		between: (Character value: 8804)
																		and: (Character value: 8805))
																		or: [ currentCharacter =
																				(Character value: 8901) ] ] ] ] ] ] ] ] ])
		ifTrue:
			[ self scan31X1 ].
	^ self reportLastMatch