generated
scan70X2
	currentCharacter == $\
		ifTrue: [ ^ self scan38 ].
	currentCharacter == $h
		ifTrue: [ ^ self scan71 ].
	currentCharacter == $t
		ifTrue: [ ^ self scan72 ].
	(currentCharacter == $'
		or: [ (currentCharacter between: $0 and: $9)
				or: [ (currentCharacter between: $A and: $Z)
						or: [ currentCharacter == $_
								or: [ (currentCharacter between: $a and: $g)
										or: [ (currentCharacter between: $i and: $s)
												or: [ (currentCharacter between: $u and: $z)
														or: [ ('µæ' includes: currentCharacter)
																or: [ currentCharacter =
																		(Character value: 960) ] ] ] ] ] ] ] ])
		ifTrue: [ ^ self scan46 ].
	^ self scan70X1